apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 5000
    targetPort: 9000
    nodePort: 31000
  selector:
    app: frontend